#pragma once
////IntroGameScene
#define SCENE_TRANSITION_TIME 1.0f
#define SPLASH_SCENE_SHOW_TIME 3.0f
#define INTRO_GAME_SCENE_BACKGROUND_FILEPATH "Logo.png"

////MainMenuScene
#define MAIN_MENU_SCENE_BACKGROUND_FILEPATH "BackGroundMenu.png"
#define MAIN_MENU_SCENE_MUSIC_BUTTON_FILEPATH "BTMusic.png"
#define MAIN_MENU_SCENE_MUSIC_XBUTTON_FILEPATH "BTxMusic.png"
#define MAIN_MENU_SCENE_SOUND_BUTTON_FILEPATH "BTSound.png"
#define MAIN_MENU_SCENE_SOUND_XBUTTON_FILEPATH "BTxSound.png"
#define MAIN_MENU_SCENE_PLAY_BUTTON_FILEPATH "BTPlay.png"
#define MAIN_MENU_SCENE_SHOP_BUTTON_FILEPATH "BTShop.png"
#define MAIN_MENU_SCENE_FONT_FILEPATH "fontVN.otf"
//Sound
#define MAIN_MENU_SCENE_MUSIC_BACKGROUND_FILEPATH "NhacNenGameHamster.wav"


////MainGameScene
#define MAIN_GAME_SCENE_BACKGROUND_FILEPATH "BackgroundPlay(1).png"
#define MAIN_GAME_SCENE_MOUSE_ITEM_DEFAULT_FILEPATH "ChuotPlay.png"
#define MAIN_GAME_SCENE_MOUSE_ITEM_FIRST_FILEPATH "ChuotPlaySkin1.png"
#define MAIN_GAME_SCENE_COIN_BUTTON_FILEPATH "BTCoin.png"
#define MAIN_GAME_SCENE_RATE_BUTTON_FILEPATH "BTRate.png"
#define MAIN_GAME_SCENE_CORN_ITEM_FILEPATH "Corn.png"
#define MAIN_GAME_SCENE_PEPPER_ITEM_FILEPATH "Pepper.png"
#define MAIN_GAME_SCENE_GOLD_ITEM_FILEPATH "DongTien.png"
//Sound
#define MAIN_GAME_SCENE_EAT_SOUND_FILEPATH "Nhai.mp3"
#define MAIN_GAME_SCENE_DIE_SOUND_FILEPATH "Die.mp3"
#define MAIN_GAME_SCENE_EAT_GOLD_SOUND_FILEPATH "AnVang.mp3"
//Font
#define MAIN_GAME_SCENE_FONT_FILEPATH "VAVON.otf"

////FinishGameScene
#define FINISH_GAME_SCENE_BACKGROUND_FILEPATH "EndGame.png"
#define FINISH_GAME_SCENE_NEWBEST_FILEPATH "NewBest.png"
#define FINISH_GAME_SCENE_REPLAY_BUTTON_FILEPATH "BTReplay.png"
#define FINISH_GAME_SCENE_BACK_BUTTON_FILEPATH "BTBack.png"
#define FINISH_GAME_SCENE_SHAREFB_BUTTON_FILEPATH "BTFacebook.png"
////ShopScene
#define SHOP_SCENE_BACKGROUND_FILEPATH "BackGroundShop.png"
#define SHOP_SCENE_DEFAULT_SKIN_FILEPATH "XSkin.png"
#define SHOP_SCENE_DEFAULT_SMALL_SKIN_FILEPATH "XSmallSkin.png"
#define SHOP_SCENE_BUY_BUTTON_FILEPATH "BTBuy.png"
#define SHOP_SCENE_BOUGHT_BUTTON_FILEPATH  "BTxBuy.png"
#define SHOP_SCENE_1_SMALL_SKIN_FILEPATH "SkinSmall1.png"
#define SHOP_SCENE_1_SKIN_FILEPATH "Skin1.png"
#define SHOP_SCENE_2_SMALL_SKIN_FILEPATH "SkinSmall2.png"
#define SHOP_SCENE_2_SKIN_FILEPATH "Skin2.png"
////Popup
#define POPUP_SCENE_BACKGROUND_FILEPATH "BackGroundPopup.png"